{
  description = "dox-populi: a Screeps client specified in Paradox, soup to nuts via nix";

  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";

    paradox.url = "gitlab:paradox_labs/paradox";

    typed-screeps = {
      url = "github:screepers/typed-screeps";
      flake = false;
    };

    secrix.url = "github:Platonic-Systems/secrix";

    disko = {
      url = "https://flakehub.com/f/nix-community/disko/1.13.0.tar.gz";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    determinate.url = "https://flakehub.com/f/DeterminateSystems/determinate/3";
  };

  outputs = { self, nixpkgs, paradox, typed-screeps, secrix, disko, determinate }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
      # Every locked flake input source, recursively; baked into the VM
      # image so the guest's first `nix develop` fetches nothing.
      collectFlakeInputs = input:
        [ input ] ++ builtins.concatMap collectFlakeInputs
          (builtins.attrValues (input.inputs or { }));
      flakeInputSources =
        builtins.concatMap collectFlakeInputs (builtins.attrValues self.inputs);
      # Shared by nixosConfigurations.vm and checks.vm-boot.
      vmCoreModules = [
        determinate.nixosModules.default
        ./vm/module.nix
      ];
      paradoxBin = paradox.packages.${system}.paradox;
      # Atlas lives in the paradox *source* (the flake input), not the
      # installed package output.
      atlas = "${paradox}/lib/dox";

      # Paradox generate writes into <spec-dir>/.dox/, so work on a copy.
      generated = pkgs.stdenv.mkDerivation {
        name = "dox-populi-generated";
        src = ./dox;
        nativeBuildInputs = [ paradoxBin pkgs.z3 ];
        PARADOX_ATLAS = atlas;
        LC_ALL = "C.UTF-8"; # GHC decodes source files per locale; sandbox has none
        buildPhase = ''
          cp -r . ../spec
          paradox generate --typescript --path ../spec
        '';
        installPhase = ''
          mkdir -p $out
          cp -r ../spec/.dox/. $out/
        '';
      };

      # Assemble the full TS project (harness + generated + vendored types).
      tsSrc = pkgs.runCommand "dox-populi-ts-src" { } ''
        mkdir -p $out/vendor
        cp -r ${./harness} $out/harness
        cp -r ${generated} $out/generated
        cp ${typed-screeps}/dist/index.d.ts $out/vendor/screeps.d.ts
        cp ${./tsconfig.json} $out/tsconfig.json
      '';

      main = pkgs.stdenv.mkDerivation {
        name = "dox-populi-main";
        src = tsSrc;
        nativeBuildInputs = [ pkgs.esbuild ];
        buildPhase = ''
          esbuild harness/main.ts --bundle --format=cjs --platform=node \
            --outfile=main.js
        '';
        installPhase = ''
          mkdir -p $out
          cp main.js $out/
        '';
      };
      # secrix CLI as a devShell command (llm-core pattern: tool packages
      # included in devShell packages, not reached via `nix run`).
      secrixApp = secrix.secrix self;
      secrixCli = pkgs.writeShellApplication {
        name = "secrix";
        text = ''
          exec ${secrixApp.program} "$@"
        '';
      };

      # Supported hardware and host requirements — the single
      # declaration. Supported host: Linux x86_64, KVM recommended
      # (TCG works, slowly). run-vm.sh is rendered from these
      # constants (nix run .#gen-run-vm); checks.run-vm-fresh fails
      # when the committed copy drifts; the tests take their VM
      # sizing from here.
      hardware = {
        hostDependencies = [ "qemu" "tmux" "curl" ];
        installMemMiB = 4096; # installer boot: dd + growpart only
        installCpus = 4;
        runMemMiB = 32768; # dev VM: server children + world db in memory
        runCpus = 8;
        bootTestMemMiB = 16384; # vm-boot check: first-boot contract only
        diskSize = "40G"; # qcow2 virtual size; the 16G image grows into it
        ports = { ssh = 2222; http = 21025; cli = 21026; client = 8080; };
        # Download source for the released installer ISO (Hetzner).
        # Empty until the first release is published; set it, rerun
        # gen-run-vm, and run-vm.sh self-serves the download.
        isoUrl = "";
      };
      memG = mib: "${toString (mib / 1024)}G";

      # The committed ./run-vm.sh, rendered from the hardware
      # contract. Plain bash, zero nix: it is the file non-nix users
      # download, so it must never invoke or assume nix in the reader
      # path.
      runVmSh = pkgs.writeText "run-vm.sh" ''
        #!/usr/bin/env bash
        # GENERATED by `nix run .#gen-run-vm` from the hardware constants in
        # flake.nix — DO NOT EDIT MANUALLY. checks.run-vm-fresh fails when
        # this file drifts from the flake.
        #
        # dox-populi dev VM runner: starts qemu detached in a tmux session
        # with its serial console on stdio; `./run-vm.sh console` attaches
        # to it.
        #
        # Host dependencies: ${pkgs.lib.concatStringsSep ", " hardware.hostDependencies}. NO nix — nix runs INSIDE
        # the VM. Supported host: Linux x86_64; KVM recommended
        # (unaccelerated works, slowly).
        #
        # First run: obtains dox-populi-installer.iso (from beside this
        # script, from a maintainer build in ./result/iso/, or downloaded
        # from ISO_URL), creates the VM disk, and boots the ISO once — its
        # boot service dd's the prebuilt system image onto the disk and
        # powers off. Every run after that boots the installed system.
        #
        # Delete dox-populi.qcow2 for a factory reset (then rerun).
        #
        # Commands:
        #   ./run-vm.sh [start]      start the VM (first run installs first)
        #   ./run-vm.sh console      connect to the serial console (Ctrl-b d = detach)
        #   ./run-vm.sh send <cmd>   type a command into the console
        #   ./run-vm.sh status       is the VM running?
        #   ./run-vm.sh kill         stop the VM
        #
        # The guest is a full NixOS dev environment (see vm/module.nix). Log in
        # on the serial console (auto-login as `dev`) or:
        #
        #   ssh -p ${toString hardware.ports.ssh} dev@localhost   # password: dox-populi
        #
        # The Steam client on the host connects to localhost:${toString hardware.ports.http}; the local
        # browser client (nix run .#client inside the VM) is served at
        # localhost:${toString hardware.ports.client}.
        #
        # Env knobs (all optional): MEM (default ${memG hardware.runMemMiB}), CPUS (default ${toString hardware.runCpus}), DISK
        # (default ./dox-populi.qcow2), DISK_SIZE (default ${hardware.diskSize}, first run
        # only), ISO (default ./dox-populi-installer.iso), ISO_URL (where to
        # download the ISO; empty until a release is published), WORKDIR
        # (host dir shared into the guest at ~/work; default: ~/vm-keys,
        # skipped if it doesn't exist).
        set -euo pipefail

        REPO="$(cd "$(dirname "$0")" && pwd)"
        DISK="''${DISK:-dox-populi.qcow2}"
        DISK_SIZE="''${DISK_SIZE:-${hardware.diskSize}}"
        ISO="''${ISO:-$REPO/dox-populi-installer.iso}"
        ISO_URL="''${ISO_URL:-${hardware.isoUrl}}"
        WORKDIR="''${WORKDIR:-$HOME/vm-keys}"
        MEM="''${MEM:-${memG hardware.runMemMiB}}"
        CPUS="''${CPUS:-${toString hardware.runCpus}}"
        INSTALL_MEM="''${INSTALL_MEM:-${memG hardware.installMemMiB}}"
        INSTALL_CPUS="''${INSTALL_CPUS:-${toString hardware.installCpus}}"
        SESSION="''${SESSION:-dox-populi-vm}"

        # KVM where writable, TCG emulation otherwise (works, slowly).
        ACCEL=()
        detect_accel() {
          if [ -w /dev/kvm ]; then
            ACCEL=(-enable-kvm -cpu host)
          else
            echo "warning: /dev/kvm not writable — running unaccelerated (slow)" >&2
          fi
        }

        CMD="''${1:-start}"
        [ $# -gt 0 ] && shift

        case "$CMD" in

          console)
            exec tmux attach-session -t "$SESSION"
            ;;

          send)
            exec tmux send-keys -t "$SESSION" "$*" C-m
            ;;

          status)
            if tmux has-session -t "$SESSION" 2>/dev/null; then
              echo "running (connect: $0 console)"
            else
              echo "not running"
            fi
            exit 0
            ;;

          kill)
            # Kill the tmux session (takes qemu with it) and reap any stray
            # qemu on our disk from older runs outside tmux.
            tmux kill-session -t "$SESSION" 2>/dev/null || true
            pkill -f "qemu-system-x86_64.*$DISK" 2>/dev/null || true
            echo "stopped"
            exit 0
            ;;

          start)
            if ! command -v tmux >/dev/null 2>&1; then
              echo "error: tmux is required (it hosts the VM's serial console)" >&2
              exit 1
            fi
            # Resolve qemu here and hand the absolute path into the tmux
            # session: tmux spawns sessions with its own environment, which may
            # not have this shell's PATH (e.g. qemu from a dev shell).
            if ! QEMU="$(command -v qemu-system-x86_64)"; then
              echo "error: qemu-system-x86_64 is required (install qemu on the host)" >&2
              exit 1
            fi
            if tmux has-session -t "$SESSION" 2>/dev/null; then
              echo "already running — connect: $0 console"
              exit 0
            fi

            if [ ! -f "$DISK" ]; then
              # First run: obtain the ISO, create the disk, boot the
              # installer in the foreground (it powers itself off).
              if [ ! -f "$ISO" ]; then
                MAINT_ISO=$(set -- "$REPO"/result/iso/*.iso; echo "$1")
                if [ -f "$MAINT_ISO" ]; then
                  ISO="$MAINT_ISO"
                elif [ -n "$ISO_URL" ]; then
                  if ! command -v curl >/dev/null 2>&1; then
                    echo "error: curl is required (it downloads the installer ISO)" >&2
                    exit 1
                  fi
                  echo "downloading the dox-populi installer ISO (one-time)..."
                  curl -fL -o "$ISO" "$ISO_URL"
                else
                  echo "error: installer ISO not found: $ISO" >&2
                  echo "" >&2
                  echo "Download dox-populi-installer.iso from the project's releases and" >&2
                  echo "place it next to this script, or set ISO_URL= to fetch it" >&2
                  echo "automatically. Maintainers build it with: nix build .#installer-iso" >&2
                  exit 1
                fi
              fi
              detect_accel
              qemu-img create -f qcow2 "$DISK" "$DISK_SIZE"
              echo "created $DISK ($DISK_SIZE) — installing (dd, grow, poweroff)..."
              # No -netdev: the installer needs no network.
              "$QEMU" \
                "''${ACCEL[@]}" \
                -m "$INSTALL_MEM" -smp "$INSTALL_CPUS" \
                -drive "file=$DISK,if=virtio,format=qcow2" \
                -cdrom "$ISO" -boot d \
                -display none \
                -serial mon:stdio \
                || { echo "error: installer qemu exited abnormally — delete $DISK and retry" >&2; exit 1; }
              echo "install complete — booting the installed system"
            fi

            tmux new-session -d -s "$SESSION" \
              "DISK=$(printf %q "$DISK") MEM=$(printf %q "$MEM") \
               CPUS=$(printf %q "$CPUS") \
               QEMU=$(printf %q "$QEMU") \
               WORKDIR=$(printf %q "''${WORKDIR:-}") $(printf %q "$0") _qemu"

            echo "VM started — serial console: $0 console   (Ctrl-b d = detach)"
            exit 0
            ;;

          # Internal: runs qemu in the foreground of the tmux session, serial
          # console on stdio.
          _qemu)
            detect_accel

            # Shares the repo read-write into the guest.
            SHARE=(-virtfs "local,path=$REPO,mount_tag=repodir,security_model=mapped-xattr")

            if [ -n "''${WORKDIR:-}" ] && [ -d "$WORKDIR" ]; then
              SHARE+=(-virtfs "local,path=$WORKDIR,mount_tag=workdir,security_model=mapped-xattr")

              # Hard-links the game's package.nw into the shared dir, where
              # `nix run .#client` inside the VM reads it: the browser client
              # serves the game from these assets. Re-linked whenever the
              # source file changes (new inode).
              NW="''${SCREEPS_CLIENT_NW:-$HOME/.local/share/Steam/steamapps/common/Screeps/package.nw}"
              if [ -f "$NW" ]; then
                NW=$(readlink -f "$NW")
                if ! [ "$WORKDIR/package.nw" -ef "$NW" ]; then
                  ln -f "$NW" "$WORKDIR/package.nw" 2>/dev/null \
                    || cp -f "$NW" "$WORKDIR/package.nw"
                  echo "linked client assets into $WORKDIR/package.nw"
                fi
              fi
            fi

            # Port forwards: ${toString hardware.ports.ssh} -> sshd, ${toString hardware.ports.http}/${toString hardware.ports.cli} -> Screeps server + CLI
            # (the host Steam client connects to localhost:${toString hardware.ports.http}), ${toString hardware.ports.client} -> the
            # browser client bridge (nix run .#client inside the VM).
            "''${QEMU:-qemu-system-x86_64}" \
              "''${ACCEL[@]}" \
              -m "$MEM" -smp "$CPUS" \
              -drive "file=$DISK,if=virtio,format=qcow2" \
              -netdev user,id=net0,hostfwd=tcp::${toString hardware.ports.ssh}-:22,hostfwd=tcp::${toString hardware.ports.http}-:${toString hardware.ports.http},hostfwd=tcp::${toString hardware.ports.cli}-:${toString hardware.ports.cli},hostfwd=tcp::${toString hardware.ports.client}-:${toString hardware.ports.client} \
              -device virtio-net-pci,netdev=net0 \
              "''${SHARE[@]}" \
              -display none \
              -serial mon:stdio \
              || { echo; echo "[qemu exited: $?] press Enter to close"; read -r; }
            ;;

          *)
            echo "usage: $0 [start|console|send <cmd>|status|kill]" >&2
            exit 1
            ;;
        esac
      '';
    in
    {
      # Dev VM. Built into a raw disk image (packages.vm-image →
      # vm-image-zst) that the installer ISO dd's onto /dev/vda.
      # vm/disko.nix is a separate module so checks.vm-boot can boot
      # vmCoreModules without it.
      nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = vmCoreModules ++ [
          disko.nixosModules.disko
          ./vm/disko.nix
          # Bake dev-shell outputs and all locked flake input sources
          # into the image so `nix develop` in the VM is offline. Lives
          # here because it needs `self`; vm/module.nix stays self-free
          # for tests/vm.nix.
          {
            system.extraDependencies = flakeInputSources ++ [
              self.devShells.${system}.default
            ];
          }
        ];
      };
      nixosConfigurations.installer = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { vmImageZst = self.packages.${system}.vm-image-zst; };
        modules = [ ./vm/installer.nix ];
      };

      packages.${system} = {
        inherit generated main;
        secrix = secrixCli;
        default = main;
        # Raw disk image of the dev VM (disko image builder). Output:
        # <name>.raw per disk (vm/disko.nix names one disk, "main").
        vm-image =
          self.nixosConfigurations.vm.config.system.build.diskoImages;
        # zstd -3: ~100x faster than -19 for <3% size difference.
        vm-image-zst = pkgs.runCommand "dox-populi-vm-image-zst"
          { nativeBuildInputs = [ pkgs.zstd ]; } ''
          mkdir -p $out
          zstd -3 -T0 -v -o $out/image.raw.zst \
            ${self.packages.${system}.vm-image}/*.raw
        '';
        installer-iso =
          self.nixosConfigurations.installer.config.system.build.isoImage;
      };

      devShells.${system}.default = pkgs.mkShell {
        name = "dox-populi-dev";
        packages = [
          paradoxBin
          pkgs.z3
          pkgs.nodejs
          pkgs.typescript
          pkgs.esbuild
          pkgs.age
          pkgs.jq
          pkgs.curl
          pkgs.nixpkgs-fmt
          self.packages.${system}.secrix
        ];
        PARADOX_ATLAS = atlas;
        shellHook = ''
          echo "dox-populi Development Shell"
          echo ""
          echo "Available commands:"
          echo "  paradox check --path dox      — verify the spec"
          echo "  secrix create|edit|rekey ...  — manage encrypted secrets"
          echo "  nix run .#generate            — write ./generated + ./vendor for editors"
          echo "  nix run .#deploy              — bundle and push main.js to Screeps"
          echo "  nix run .#installer-iso       — provision the dev VM disk (one-time dd install)"
          echo "  nix run .#gen-run-vm          — regenerate run-vm.sh after hardware changes"
          echo "  ./run-vm.sh                   — run the installed dev VM"
          echo "  nix flake check               — run all checks"
        '';
      };

      checks.${system} = {
        paradox-check = pkgs.runCommand "paradox-check"
          {
            nativeBuildInputs = [ paradoxBin pkgs.z3 ];
            PARADOX_ATLAS = atlas;
            LC_ALL = "C.UTF-8";
          } ''
          cp -r ${./dox} spec
          chmod -R u+w spec
          paradox check --path spec
          touch $out
        '';

        typecheck = pkgs.runCommand "typecheck"
          { nativeBuildInputs = [ pkgs.typescript ]; } ''
          cp -r ${tsSrc}/. .
          tsc --noEmit -p tsconfig.json
          touch $out
        '';

        # First-boot contract of the dev VM (vmCoreModules): repo
        # mount, sshd, Determinate Nix, flakes, dev env vars.
        vm-boot = pkgs.callPackage ./tests/vm.nix {
          nixosModule = { imports = vmCoreModules; };
          inherit self;
          memorySize = hardware.bootTestMemMiB;
        };

        # The committed run-vm.sh must byte-match what the flake
        # renders from the hardware constants.
        run-vm-fresh = pkgs.runCommand "run-vm-fresh" { } ''
          if ! diff -u ${./run-vm.sh} ${runVmSh}; then
            echo "run-vm.sh is stale — regenerate with: nix run .#gen-run-vm" >&2
            exit 1
          fi
          touch $out
        '';

        build = main;
      };

      apps.${system} = {
        # Regenerate ./generated and ./vendor in the working tree for editor use.
        generate = {
          type = "app";
          program = toString (pkgs.writeShellScript "generate" ''
            set -euo pipefail
            rm -rf generated vendor
            mkdir -p generated vendor
            cp -r ${generated}/. generated/
            cp ${typed-screeps}/dist/index.d.ts vendor/screeps.d.ts
            chmod -R u+w generated vendor
            echo "wrote ./generated and ./vendor/screeps.d.ts"
          '');
        };

        # Human-gated deploy: decrypting the token requires the SSH private key.
        deploy = {
          type = "app";
          program = toString (pkgs.writeShellScript "deploy" ''
            set -euo pipefail
            IDENTITY="''${SCREEPS_IDENTITY:-$HOME/.ssh/gitlab}"
            TOKEN=$(${pkgs.age}/bin/age -d -i "$IDENTITY" secrets/SCREEPS_TOKEN)
            ${pkgs.jq}/bin/jq -n --arg code "$(cat ${main}/main.js)" \
              '{branch: "default", modules: {main: $code}}' \
            | ${pkgs.curl}/bin/curl --fail-with-body -X POST \
                "https://screeps.com/api/user/code" \
                -H "X-Token: $TOKEN" \
                -H "Content-Type: application/json" \
                --data @-
            echo
            echo "deployed main.js to branch 'default'"
          '');
        };

        # Regenerate ./run-vm.sh from the hardware constants and stage
        # it. The committed copy is the file non-nix users download.
        gen-run-vm = {
          type = "app";
          program = toString (pkgs.writeShellScript "gen-run-vm" ''
            set -euo pipefail
            cd "$(${pkgs.git}/bin/git rev-parse --show-toplevel)"
            install -m 755 ${runVmSh} run-vm.sh
            ${pkgs.git}/bin/git add run-vm.sh
            echo "wrote run-vm.sh (staged; commit when ready)"
          '');
        };

        # Provision the dev VM disk (one-time): create dox-populi.qcow2
        # and boot the installer ISO in qemu; its boot service dd's the
        # prebuilt image onto the disk and powers off (vm/installer.nix).
        # No -netdev: the installer needs no network. ./run-vm.sh runs
        # the installed VM. `nix run .#installer-iso` resolves to this
        # app; `nix build .#installer-iso` builds the bare ISO package.
        installer-iso = {
          type = "app";
          program = toString (pkgs.writeShellScript "install-vm" ''
            set -euo pipefail
            DISK="''${DISK:-$(${pkgs.git}/bin/git rev-parse --show-toplevel)/dox-populi.qcow2}"
            DISK_SIZE="''${DISK_SIZE:-${hardware.diskSize}}"
            MEM="''${MEM:-${memG hardware.installMemMiB}}"
            CPUS="''${CPUS:-${toString hardware.installCpus}}"
            if [ -f "$DISK" ]; then
              echo "error: $DISK already exists — the VM is already installed." >&2
              echo "run it with ./run-vm.sh, or delete the disk for a factory reset." >&2
              exit 1
            fi
            ISO=$(set -- ${self.packages.${system}.installer-iso}/iso/*.iso; echo "$1")
            ACCEL=()
            if [ -w /dev/kvm ]; then
              ACCEL=(-enable-kvm -cpu host)
            else
              echo "warning: /dev/kvm not writable — running unaccelerated (slow)" >&2
            fi
            ${pkgs.qemu}/bin/qemu-img create -f qcow2 "$DISK" "$DISK_SIZE"
            echo "created $DISK ($DISK_SIZE) — booting the installer (dd, grow, poweroff)..."
            ${pkgs.qemu}/bin/qemu-system-x86_64 \
              "''${ACCEL[@]}" \
              -m "$MEM" -smp "$CPUS" \
              -drive "file=$DISK,if=virtio,format=qcow2" \
              -cdrom "$ISO" -boot d \
              -display none \
              -serial mon:stdio \
              || { echo "error: installer qemu exited abnormally — delete $DISK and retry" >&2; exit 1; }
            echo ""
            echo "install complete — boot the dev VM with ./run-vm.sh"
          '');
        };

        secrix = secrix.secrix self;
      };
    };
}
