#!/usr/bin/env bash
# GENERATED by `nix run .#gen-run-vm` from the hardware constants in
# flake.nix — DO NOT EDIT MANUALLY. checks.run-vm-fresh fails when
# this file drifts from the flake.
#
# dox-populi dev VM runner: starts qemu detached in a tmux session
# with its serial console on stdio; `./run-vm.sh console` attaches
# to it.
#
# Host dependencies: qemu, tmux, curl. NO nix — nix runs INSIDE
# the VM. Supported host: Linux x86_64; KVM recommended
# (unaccelerated works, slowly).
#
# First run: obtains dox-populi-compact.qcow2 (place it beside
# this script, set IMAGE_URL to download it, or build it with
# `nix run .#installer-iso`). Every run boots that disk.
#
# Delete dox-populi-compact.qcow2 for a factory reset (then rerun).
#
# Commands:
#   ./run-vm.sh [start]      start the VM (first run installs first)
#   ./run-vm.sh console      connect to the serial console (Ctrl-b d = detach)
#   ./run-vm.sh send <cmd>   type a command into the console
#   ./run-vm.sh status       is the VM running?
#   ./run-vm.sh kill         stop the VM
#
# The guest is a full NixOS dev environment (see vm/module.nix). Log in
# on the serial console (auto-login as `dev`) or:
#
#   ssh -p 2222 dev@localhost   # password: dox-populi
#
# The Steam client on the host connects to localhost:21025; the local
# browser client (nix run .#client inside the VM) is served at
# localhost:8080.
#
# Env knobs (all optional): MEM, CPUS (default: half the host's
# memory and cores, capped at 32G/8), DISK
# (default ./dox-populi-compact.qcow2), IMAGE_URL (where to
# download the image; empty until a release is published), WORKDIR
# (host dir shared into the guest at ~/work; default: ~/vm-keys,
# skipped if it doesn't exist).
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
DISK="${DISK:-dox-populi-compact.qcow2}"
IMAGE_URL="${IMAGE_URL:-}"
WORKDIR="${WORKDIR:-$HOME/vm-keys}"
# Auto-size from the host: half its memory and cores, capped at
# the declared hardware contract. MEM=, CPUS= override.
HOST_MEM_MIB=1024
while read -r key val _; do
  if [ "$key" = "MemTotal:" ]; then HOST_MEM_MIB=$((val / 1024)); break; fi
done < /proc/meminfo
HOST_CPUS=$(nproc 2>/dev/null || echo 1)
AUTO_MEM=$((HOST_MEM_MIB / 2))
[ "$AUTO_MEM" -gt 32768 ] && AUTO_MEM=32768
AUTO_CPUS=$((HOST_CPUS / 2))
[ "$AUTO_CPUS" -lt 1 ] && AUTO_CPUS=1
[ "$AUTO_CPUS" -gt 8 ] && AUTO_CPUS=8
MEM="${MEM:-${AUTO_MEM}M}"
CPUS="${CPUS:-$AUTO_CPUS}"
SESSION="${SESSION:-dox-populi-vm}"

# KVM where writable, TCG emulation otherwise (works, slowly).
ACCEL=()
detect_accel() {
  if [ -w /dev/kvm ]; then
    ACCEL=(-enable-kvm -cpu host)
  else
    echo "warning: /dev/kvm not writable — running unaccelerated (slow)" >&2
  fi
}

CMD="${1:-start}"
[ $# -gt 0 ] && shift

case "$CMD" in

  console)
    exec tmux attach-session -t "$SESSION"
    ;;

  send)
    exec tmux send-keys -t "$SESSION" "$*" C-m
    ;;

  status)
    if tmux has-session -t "$SESSION" 2>/dev/null; then
      echo "running (connect: $0 console)"
    else
      echo "not running"
    fi
    exit 0
    ;;

  kill)
    # Kill the tmux session (takes qemu with it) and reap any stray
    # qemu on our disk from older runs outside tmux.
    tmux kill-session -t "$SESSION" 2>/dev/null || true
    pkill -f "qemu-system-x86_64.*$DISK" 2>/dev/null || true
    echo "stopped"
    exit 0
    ;;

  start)
    if ! command -v tmux >/dev/null 2>&1; then
      echo "error: tmux is required (it hosts the VM's serial console)" >&2
      exit 1
    fi
    # Resolve qemu here and hand the absolute path into the tmux
    # session: tmux spawns sessions with its own environment, which may
    # not have this shell's PATH (e.g. qemu from a dev shell).
    if ! QEMU="$(command -v qemu-system-x86_64)"; then
      echo "error: qemu-system-x86_64 is required (install qemu on the host)" >&2
      exit 1
    fi
    if tmux has-session -t "$SESSION" 2>/dev/null; then
      echo "already running — connect: $0 console"
      exit 0
    fi

    if [ ! -f "$DISK" ]; then
      # First run: obtain the VM image.
      if [ -n "$IMAGE_URL" ]; then
        if ! command -v curl >/dev/null 2>&1; then
          echo "error: curl is required (it downloads the VM image)" >&2
          exit 1
        fi
        echo "downloading the dox-populi VM image (one-time)..."
        curl -fL -o "$DISK" "$IMAGE_URL"
      else
        echo "error: VM image not found: $DISK" >&2
        echo "" >&2
        echo "Download dox-populi-compact.qcow2 from the project's releases and" >&2
        echo "place it next to this script, or set IMAGE_URL= to fetch it" >&2
        echo "automatically. Maintainers build it with: nix run .#installer-iso" >&2
        exit 1
      fi
    fi

    tmux new-session -d -s "$SESSION" \
      "DISK=$(printf %q "$DISK") MEM=$(printf %q "$MEM") \
       CPUS=$(printf %q "$CPUS") \
       QEMU=$(printf %q "$QEMU") \
       WORKDIR=$(printf %q "${WORKDIR:-}") $(printf %q "$0") _qemu"

    echo "VM started — serial console: $0 console   (Ctrl-b d = detach)"
    exit 0
    ;;

  # Internal: runs qemu in the foreground of the tmux session, serial
  # console on stdio.
  _qemu)
    detect_accel

    # Shares the repo read-write into the guest.
    SHARE=(-virtfs "local,path=$REPO,mount_tag=repodir,security_model=mapped-xattr")

    if [ -n "${WORKDIR:-}" ] && [ -d "$WORKDIR" ]; then
      SHARE+=(-virtfs "local,path=$WORKDIR,mount_tag=workdir,security_model=mapped-xattr")

      # Hard-links the game's package.nw into the shared dir, where
      # `nix run .#client` inside the VM reads it: the browser client
      # serves the game from these assets. Re-linked whenever the
      # source file changes (new inode).
      NW="${SCREEPS_CLIENT_NW:-$HOME/.local/share/Steam/steamapps/common/Screeps/package.nw}"
      if [ -f "$NW" ]; then
        NW=$(readlink -f "$NW")
        if ! [ "$WORKDIR/package.nw" -ef "$NW" ]; then
          ln -f "$NW" "$WORKDIR/package.nw" 2>/dev/null \
            || cp -f "$NW" "$WORKDIR/package.nw"
          echo "linked client assets into $WORKDIR/package.nw"
        fi
      fi
    fi

    # Port forwards: 2222 -> sshd, 21025/21026 -> Screeps server + CLI
    # (the host Steam client connects to localhost:21025), 8080 -> the
    # browser client bridge (nix run .#client inside the VM).
    "${QEMU:-qemu-system-x86_64}" \
      "${ACCEL[@]}" \
      -m "$MEM" -smp "$CPUS" \
      -drive "file=$DISK,if=virtio,format=qcow2" \
      -netdev user,id=net0,hostfwd=tcp::2222-:22,hostfwd=tcp::21025-:21025,hostfwd=tcp::21026-:21026,hostfwd=tcp::8080-:8080 \
      -device virtio-net-pci,netdev=net0 \
      "${SHARE[@]}" \
      -display none \
      -serial mon:stdio \
      || { echo; echo "[qemu exited: $?] press Enter to close"; read -r; }
    ;;

  *)
    echo "usage: $0 [start|console|send <cmd>|status|kill]" >&2
    exit 1
    ;;
esac
