{ pkgs, self, system, nixpkgs, disko, determinate, flakeInputSources }:

let
  # Shared by nixosConfigurations.vm and checks.vm-boot.
  vmCoreModules = [
    determinate.nixosModules.default
    ./module.nix
  ];

  # Supported hardware and host requirements — the single
  # declaration. Supported host: Linux x86_64, KVM recommended
  # (TCG works, slowly). run-vm.sh is rendered from these
  # constants (nix run .#gen-run-vm); checks.run-vm-fresh fails
  # when the committed copy drifts; the tests take their VM
  # sizing from here.
  hardware = {
    hostDependencies = [ "qemu" "tmux" "curl" ];
    installMemMiB = 4096; # installer boot: dd + growpart only
    installCpus = 4;
    runMemMiB = 32768; # dev VM: server children + world db in memory
    runCpus = 8;
    bootTestMemMiB = 16384; # vm-boot check: first-boot contract only
    diskSize = "40G"; # qcow2 virtual size; the 16G image grows into it
    ports = { ssh = 2222; http = 21025; cli = 21026; client = 8080; };
    # Download source for the released VM image (Hetzner).
    # run-vm.sh self-serves the download from here on first run.
    imageUrl = "https://dokyard.dev/installs/dox-populi-compact.qcow2";
  };
  memG = mib: "${toString (mib / 1024)}G";

  # The committed ./run-vm.sh, rendered from the hardware
  # contract. Plain bash, zero nix: it is the file non-nix users
  # download, so it must never invoke or assume nix in the reader
  # path.
  runVmSh = pkgs.writeText "run-vm.sh" ''
    #!/usr/bin/env bash
    # GENERATED by `nix run .#gen-run-vm` from the hardware constants in
    # flake.nix — DO NOT EDIT MANUALLY. checks.run-vm-fresh fails when
    # this file drifts from the flake.
    #
    # dox-populi dev VM runner: starts qemu detached in a tmux session
    # with its serial console on stdio; `./run-vm.sh console` attaches
    # to it.
    #
    # Host dependencies: ${pkgs.lib.concatStringsSep ", " hardware.hostDependencies}. NO nix — nix runs INSIDE
    # the VM. Supported host: Linux x86_64; KVM recommended
    # (unaccelerated works, slowly).
    #
    # First run: obtains dox-populi-compact.qcow2 (place it beside
    # this script, set IMAGE_URL to download it, or build it with
    # `nix run .#installer`). Every run boots that disk.
    #
    # Delete dox-populi-compact.qcow2 for a factory reset (then rerun).
    #
    # Commands:
    #   ./run-vm.sh [start]      start the VM (first run installs first)
    #   ./run-vm.sh console      connect to the serial console (Ctrl-b d = detach)
    #   ./run-vm.sh send <cmd>   type a command into the console
    #   ./run-vm.sh status       is the VM running?
    #   ./run-vm.sh kill         stop the VM
    #
    # The guest is a full NixOS dev environment (see vm/module.nix). Log in
    # on the serial console (auto-login as `dev`) or:
    #
    #   ssh -p ${toString hardware.ports.ssh} dev@localhost   # password: dox-populi
    #
    # The Steam client on the host connects to localhost:${toString hardware.ports.http}; the local
    # browser client (nix run .#client inside the VM) is served at
    # localhost:${toString hardware.ports.client}.
    #
    # Env knobs (all optional): MEM, CPUS (default: half the host's
    # memory and cores, capped at ${memG hardware.runMemMiB}/${toString hardware.runCpus}), DISK
    # (default ./dox-populi-compact.qcow2), IMAGE_URL (where to
    # download the image; empty until a release is published), WORKDIR
    # (host dir shared into the guest at ~/work; default: ~/vm-keys,
    # skipped if it doesn't exist).
    set -euo pipefail

    REPO="$(cd "$(dirname "$0")" && pwd)"
    DISK="''${DISK:-dox-populi-compact.qcow2}"
    IMAGE_URL="''${IMAGE_URL:-${hardware.imageUrl}}"
    WORKDIR="''${WORKDIR:-$HOME/vm-keys}"
    # Auto-size from the host: half its memory and cores, capped at
    # the declared hardware contract. MEM=, CPUS=, INSTALL_MEM=,
    # INSTALL_CPUS= override.
    HOST_MEM_MIB=1024
    while read -r key val _; do
      if [ "$key" = "MemTotal:" ]; then HOST_MEM_MIB=$((val / 1024)); break; fi
    done < /proc/meminfo
    HOST_CPUS=$(nproc 2>/dev/null || echo 1)
    AUTO_MEM=$((HOST_MEM_MIB / 2))
    [ "$AUTO_MEM" -gt ${toString hardware.runMemMiB} ] && AUTO_MEM=${toString hardware.runMemMiB}
    AUTO_CPUS=$((HOST_CPUS / 2))
    [ "$AUTO_CPUS" -lt 1 ] && AUTO_CPUS=1
    [ "$AUTO_CPUS" -gt ${toString hardware.runCpus} ] && AUTO_CPUS=${toString hardware.runCpus}
    MEM="''${MEM:-''${AUTO_MEM}M}"
    CPUS="''${CPUS:-$AUTO_CPUS}"
    SESSION="''${SESSION:-dox-populi-vm}"

    # KVM where writable, TCG emulation otherwise (works, slowly).
    ACCEL=()
    detect_accel() {
      if [ -w /dev/kvm ]; then
        ACCEL=(-enable-kvm -cpu host)
      else
        echo "warning: /dev/kvm not writable — running unaccelerated (slow)" >&2
      fi
    }

    CMD="''${1:-start}"
    [ $# -gt 0 ] && shift

    case "$CMD" in

      console)
        exec tmux attach-session -t "$SESSION"
        ;;

      send)
        exec tmux send-keys -t "$SESSION" "$*" C-m
        ;;

      status)
        if tmux has-session -t "$SESSION" 2>/dev/null; then
          echo "running (connect: $0 console)"
        else
          echo "not running"
        fi
        exit 0
        ;;

      kill)
        # Kill the tmux session (takes qemu with it) and reap any stray
        # qemu on our disk from older runs outside tmux.
        tmux kill-session -t "$SESSION" 2>/dev/null || true
        pkill -f "qemu-system-x86_64.*$DISK" 2>/dev/null || true
        echo "stopped"
        exit 0
        ;;

      start)
        if ! command -v tmux >/dev/null 2>&1; then
          echo "error: tmux is required (it hosts the VM's serial console)" >&2
          exit 1
        fi
        # Resolve qemu here and hand the absolute path into the tmux
        # session: tmux spawns sessions with its own environment, which may
        # not have this shell's PATH (e.g. qemu from a dev shell).
        if ! QEMU="$(command -v qemu-system-x86_64)"; then
          echo "error: qemu-system-x86_64 is required (install qemu on the host)" >&2
          exit 1
        fi
        if tmux has-session -t "$SESSION" 2>/dev/null; then
          echo "already running — connect: $0 console"
          exit 0
        fi

        if [ ! -f "$DISK" ]; then
          # First run: obtain the VM image.
          if [ -n "$IMAGE_URL" ]; then
            if ! command -v curl >/dev/null 2>&1; then
              echo "error: curl is required (it downloads the VM image)" >&2
              exit 1
            fi
            echo "downloading the dox-populi VM image (one-time)..."
            curl -fL -o "$DISK" "$IMAGE_URL"
          else
            echo "error: VM image not found: $DISK" >&2
            echo "" >&2
            echo "Download dox-populi-compact.qcow2 from the project's releases and" >&2
            echo "place it next to this script, or set IMAGE_URL= to fetch it" >&2
            echo "automatically. Maintainers build it with: nix run .#installer" >&2
            exit 1
          fi
        fi

        tmux new-session -d -s "$SESSION" \
          "DISK=$(printf %q "$DISK") MEM=$(printf %q "$MEM") \
           CPUS=$(printf %q "$CPUS") \
           QEMU=$(printf %q "$QEMU") \
           WORKDIR=$(printf %q "''${WORKDIR:-}") $(printf %q "$0") _qemu"

        echo "VM started — serial console: $0 console   (Ctrl-b d = detach)"
        exit 0
        ;;

      # Internal: runs qemu in the foreground of the tmux session, serial
      # console on stdio.
      _qemu)
        detect_accel

        # Shares the repo read-write into the guest.
        SHARE=(-virtfs "local,path=$REPO,mount_tag=repodir,security_model=mapped-xattr")

        if [ -n "''${WORKDIR:-}" ] && [ -d "$WORKDIR" ]; then
          SHARE+=(-virtfs "local,path=$WORKDIR,mount_tag=workdir,security_model=mapped-xattr")

          # Hard-links the game's package.nw into the shared dir, where
          # `nix run .#client` inside the VM reads it: the browser client
          # serves the game from these assets. Re-linked whenever the
          # source file changes (new inode).
          NW="''${SCREEPS_CLIENT_NW:-$HOME/.local/share/Steam/steamapps/common/Screeps/package.nw}"
          if [ -f "$NW" ]; then
            NW=$(readlink -f "$NW")
            if ! [ "$WORKDIR/package.nw" -ef "$NW" ]; then
              ln -f "$NW" "$WORKDIR/package.nw" 2>/dev/null \
                || cp -f "$NW" "$WORKDIR/package.nw"
              echo "linked client assets into $WORKDIR/package.nw"
            fi
          fi
        fi

        # Port forwards: ${toString hardware.ports.ssh} -> sshd, ${toString hardware.ports.http}/${toString hardware.ports.cli} -> Screeps server + CLI
        # (the host Steam client connects to localhost:${toString hardware.ports.http}), ${toString hardware.ports.client} -> the
        # browser client bridge (nix run .#client inside the VM).
        "''${QEMU:-qemu-system-x86_64}" \
          "''${ACCEL[@]}" \
          -m "$MEM" -smp "$CPUS" \
          -drive "file=$DISK,if=virtio,format=qcow2" \
          -netdev user,id=net0,hostfwd=tcp::${toString hardware.ports.ssh}-:22,hostfwd=tcp::${toString hardware.ports.http}-:${toString hardware.ports.http},hostfwd=tcp::${toString hardware.ports.cli}-:${toString hardware.ports.cli},hostfwd=tcp::${toString hardware.ports.client}-:${toString hardware.ports.client} \
          -device virtio-net-pci,netdev=net0 \
          "''${SHARE[@]}" \
          -display none \
          -serial mon:stdio \
          || { echo; echo "[qemu exited: $?] press Enter to close"; read -r; }
        ;;

      *)
        echo "usage: $0 [start|console|send <cmd>|status|kill]" >&2
        exit 1
        ;;
    esac
  '';
in
{
  inherit hardware;

  nixosConfigurations = {
    # Dev VM. Built into a raw disk image (packages.vm-image →
    # vm-image-zst) that the installer ISO dd's onto /dev/vda.
    # vm/disko.nix is a separate module so checks.vm-boot can boot
    # vmCoreModules without it.
    vm = nixpkgs.lib.nixosSystem {
      inherit system;
      modules = vmCoreModules ++ [
        disko.nixosModules.disko
        ./disko.nix
        # Bake dev-shell outputs and all locked flake input sources
        # into the image so `nix develop` in the VM is offline. Lives
        # here because it needs `self`; vm/module.nix stays self-free
        # for tests/vm.nix.
        {
          system.extraDependencies = flakeInputSources ++ [
            self.devShells.${system}.default
            self.packages.${system}.screeps-server
            self.packages.${system}.screeps-viewer
          ];
        }
      ];
    };
    installer = nixpkgs.lib.nixosSystem {
      inherit system;
      specialArgs = { vmImageZst = self.packages.${system}.vm-image-zst; };
      modules = [ ./installer.nix ];
    };
  };

  # Raw disk image of the dev VM (disko image builder). Output:
  # <name>.raw per disk (vm/disko.nix names one disk, "main").
  vm-image =
    self.nixosConfigurations.vm.config.system.build.diskoImages;
  # zstd -3: ~100x faster than -19 for <3% size difference.
  vm-image-zst = pkgs.runCommand "dox-populi-vm-image-zst"
    { nativeBuildInputs = [ pkgs.zstd ]; } ''
    mkdir -p $out
    zstd -3 -T0 -v -o $out/image.raw.zst \
      ${self.packages.${system}.vm-image}/*.raw
  '';
  installer-iso =
    self.nixosConfigurations.installer.config.system.build.isoImage;

  apps = {
    # Regenerate ./run-vm.sh from the hardware constants and stage
    # it. The committed copy is the file non-nix users download.
    gen-run-vm = {
      type = "app";
      program = toString (pkgs.writeShellScript "gen-run-vm" ''
        set -euo pipefail
        cd "$(${pkgs.git}/bin/git rev-parse --show-toplevel)"
        install -m 755 ${runVmSh} run-vm.sh
        ${pkgs.git}/bin/git add run-vm.sh
        echo "wrote run-vm.sh (staged; commit when ready)"
      '');
    };

    # Provision the dev VM disk (one-time): create dox-populi.qcow2,
    # boot the installer ISO in qemu (its boot service dd's the
    # prebuilt image onto the disk and powers off, vm/installer.nix),
    # then compact it into dox-populi-compact.qcow2 with
    # `qemu-img convert -c` and delete the uncompacted disk.
    # No -netdev: the installer needs no network. ./run-vm.sh runs
    # the installed VM. `nix run .#installer` resolves to this
    # app; `nix build .#installer-iso` builds the bare ISO package.
    installer = {
      type = "app";
      program = toString (pkgs.writeShellScript "install-vm" ''
        set -euo pipefail
        DISK="''${DISK:-$(${pkgs.git}/bin/git rev-parse --show-toplevel)/dox-populi-compact.qcow2}"
        RAW="''${RAW:-$(${pkgs.git}/bin/git rev-parse --show-toplevel)/dox-populi.qcow2}"
        DISK_SIZE="''${DISK_SIZE:-${hardware.diskSize}}"
        MEM="''${MEM:-${memG hardware.installMemMiB}}"
        CPUS="''${CPUS:-${toString hardware.installCpus}}"
        if [ -f "$DISK" ]; then
          echo "error: $DISK already exists — the VM is already installed." >&2
          echo "run it with ./run-vm.sh, or delete the disk for a factory reset." >&2
          exit 1
        fi
        ISO=$(set -- ${self.packages.${system}.installer-iso}/iso/*.iso; echo "$1")
        ACCEL=()
        if [ -w /dev/kvm ]; then
          ACCEL=(-enable-kvm -cpu host)
        else
          echo "warning: /dev/kvm not writable — running unaccelerated (slow)" >&2
        fi
        ${pkgs.qemu}/bin/qemu-img create -f qcow2 "$RAW" "$DISK_SIZE"
        echo "created $RAW ($DISK_SIZE) — booting the installer (dd, grow, poweroff)..."
        ${pkgs.qemu}/bin/qemu-system-x86_64 \
          "''${ACCEL[@]}" \
          -m "$MEM" -smp "$CPUS" \
          -drive "file=$RAW,if=virtio,format=qcow2" \
          -cdrom "$ISO" -boot d \
          -display none \
          -serial mon:stdio \
          || { echo "error: installer qemu exited abnormally — delete $RAW and retry" >&2; exit 1; }
        echo "compacting $RAW into $DISK..."
        ${pkgs.qemu}/bin/qemu-img convert -O qcow2 -c "$RAW" "$DISK"
        rm "$RAW"
        echo ""
        echo "install complete — boot the dev VM with ./run-vm.sh"
      '');
    };
  };

  checks = {
    # First-boot contract of the dev VM (vmCoreModules): repo
    # mount, sshd, Determinate Nix, flakes, dev env vars.
    vm-boot = pkgs.callPackage ../tests/vm.nix {
      nixosModule = { imports = vmCoreModules; };
      inherit self;
      memorySize = hardware.bootTestMemMiB;
    };

    # The committed run-vm.sh must byte-match what the flake
    # renders from the hardware constants.
    run-vm-fresh = pkgs.runCommand "run-vm-fresh" { } ''
      if ! diff -u ${../run-vm.sh} ${runVmSh}; then
        echo "run-vm.sh is stale — regenerate with: nix run .#gen-run-vm" >&2
        exit 1
      fi
      touch $out
    '';
  };
}
